-- Estrutura importada do SQLite; sem dados pessoais. Revisar antes de aplicar.
-- Exige migração validada e seleção explícita do runtime; este SQL não copia registros.
BEGIN;
CREATE SCHEMA IF NOT EXISTS puzoto;
REVOKE ALL ON SCHEMA puzoto FROM PUBLIC, anon, authenticated;
SET LOCAL search_path = puzoto, public;
CREATE TABLE "ajustes_retroativos" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "fechamento_mensal_id" BIGINT NOT NULL,
  "referencia" TEXT NOT NULL,
  "empresa" TEXT NOT NULL DEFAULT 'Padrão',
  "quantidade" BIGINT NOT NULL,
  "valor_unitario" DOUBLE PRECISION NOT NULL,
  "total" DOUBLE PRECISION NOT NULL,
  "observacao" TEXT,
  "criado_em" TEXT DEFAULT to_char(timezone('America/Sao_Paulo', now()), 'YYYY-MM-DD HH24:MI:SS')
);
ALTER TABLE "ajustes_retroativos" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ajustes_retroativos" FORCE ROW LEVEL SECURITY;
REVOKE ALL ON "ajustes_retroativos" FROM PUBLIC, anon, authenticated;
CREATE TABLE "auditoria" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "tipo" TEXT NOT NULL,
  "descricao" TEXT,
  "dados_antes" TEXT,
  "dados_depois" TEXT,
  "criado_em" TEXT DEFAULT to_char(timezone('America/Sao_Paulo', now()), 'YYYY-MM-DD HH24:MI:SS')
);
ALTER TABLE "auditoria" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "auditoria" FORCE ROW LEVEL SECURITY;
REVOKE ALL ON "auditoria" FROM PUBLIC, anon, authenticated;
CREATE TABLE "cartoes" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" TEXT NOT NULL,
  "banco" TEXT,
  "limite" DOUBLE PRECISION NOT NULL DEFAULT 0,
  "dia_fechamento" BIGINT NOT NULL,
  "dia_vencimento" BIGINT NOT NULL,
  "cor" TEXT,
  "icone" TEXT,
  "ativo" BIGINT DEFAULT 1,
  "criado_em" TEXT DEFAULT to_char(timezone('America/Sao_Paulo', now()), 'YYYY-MM-DD HH24:MI:SS'),
  "atualizado_em" TEXT DEFAULT to_char(timezone('America/Sao_Paulo', now()), 'YYYY-MM-DD HH24:MI:SS')
);
ALTER TABLE "cartoes" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "cartoes" FORCE ROW LEVEL SECURITY;
REVOKE ALL ON "cartoes" FROM PUBLIC, anon, authenticated;
CREATE TABLE "categorias" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" TEXT NOT NULL,
  "tipo" TEXT NOT NULL DEFAULT 'gasto',
  "cor" TEXT,
  "icone" TEXT,
  "ativa" BIGINT DEFAULT 1,
  "criado_em" TEXT DEFAULT to_char(timezone('America/Sao_Paulo', now()), 'YYYY-MM-DD HH24:MI:SS'),
  "atualizado_em" TEXT DEFAULT to_char(timezone('America/Sao_Paulo', now()), 'YYYY-MM-DD HH24:MI:SS'),
  UNIQUE ("nome")
);
ALTER TABLE "categorias" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "categorias" FORCE ROW LEVEL SECURITY;
REVOKE ALL ON "categorias" FROM PUBLIC, anon, authenticated;
CREATE TABLE "compras_cartao" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "cartao_id" BIGINT NOT NULL,
  "cartao_nome" TEXT NOT NULL,
  "descricao" TEXT NOT NULL,
  "valor_total" DOUBLE PRECISION NOT NULL,
  "categoria_id" BIGINT NOT NULL,
  "categoria_nome" TEXT NOT NULL,
  "data_compra" TEXT NOT NULL,
  "quantidade_parcelas" BIGINT NOT NULL DEFAULT 1,
  "observacao" TEXT,
  "criado_em" TEXT DEFAULT to_char(timezone('America/Sao_Paulo', now()), 'YYYY-MM-DD HH24:MI:SS'),
  "atualizado_em" TEXT DEFAULT to_char(timezone('America/Sao_Paulo', now()), 'YYYY-MM-DD HH24:MI:SS')
);
ALTER TABLE "compras_cartao" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "compras_cartao" FORCE ROW LEVEL SECURITY;
REVOKE ALL ON "compras_cartao" FROM PUBLIC, anon, authenticated;
CREATE TABLE "configuracoes" (
  "chave" TEXT PRIMARY KEY,
  "valor" TEXT,
  "atualizado_em" TEXT DEFAULT to_char(timezone('America/Sao_Paulo', now()), 'YYYY-MM-DD HH24:MI:SS')
);
ALTER TABLE "configuracoes" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "configuracoes" FORCE ROW LEVEL SECURITY;
REVOKE ALL ON "configuracoes" FROM PUBLIC, anon, authenticated;
CREATE TABLE "contas_pagar" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" TEXT NOT NULL,
  "descricao" TEXT,
  "valor" DOUBLE PRECISION NOT NULL,
  "vencimento" TEXT NOT NULL,
  "categoria_id" BIGINT NOT NULL,
  "categoria_nome" TEXT NOT NULL,
  "forma_pagamento" TEXT,
  "recorrente" BIGINT NOT NULL DEFAULT 0,
  "frequencia" TEXT DEFAULT 'nenhuma',
  "parcela_atual" BIGINT DEFAULT 1,
  "total_parcelas" BIGINT DEFAULT 1,
  "grupo_recorrencia_id" TEXT,
  "status" TEXT NOT NULL DEFAULT 'pendente',
  "pago_em" TEXT,
  "observacao" TEXT,
  "criado_em" TEXT DEFAULT to_char(timezone('America/Sao_Paulo', now()), 'YYYY-MM-DD HH24:MI:SS'),
  "atualizado_em" TEXT DEFAULT to_char(timezone('America/Sao_Paulo', now()), 'YYYY-MM-DD HH24:MI:SS'),
  CHECK (status IN ('pendente','pago','atrasado','cancelado'))
);
ALTER TABLE "contas_pagar" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "contas_pagar" FORCE ROW LEVEL SECURITY;
REVOKE ALL ON "contas_pagar" FROM PUBLIC, anon, authenticated;
CREATE TABLE "dividas_parceladas_grupos" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome_pessoa" TEXT NOT NULL,
  "tipo" TEXT NOT NULL,
  "motivo" TEXT NOT NULL,
  "valor_parcela" DOUBLE PRECISION NOT NULL,
  "valor_total_original" DOUBLE PRECISION NOT NULL DEFAULT 0,
  "total_parcelas" BIGINT NOT NULL,
  "parcelas_pagas" BIGINT NOT NULL DEFAULT 0,
  "parcelas_restantes" BIGINT NOT NULL DEFAULT 0,
  "dia_vencimento" BIGINT NOT NULL DEFAULT 5,
  "competencia_inicio" TEXT NOT NULL,
  "status" TEXT NOT NULL DEFAULT 'ativa',
  "observacao" TEXT,
  "criado_em" TEXT DEFAULT to_char(timezone('America/Sao_Paulo', now()), 'YYYY-MM-DD HH24:MI:SS'),
  "atualizado_em" TEXT DEFAULT to_char(timezone('America/Sao_Paulo', now()), 'YYYY-MM-DD HH24:MI:SS'),
  CHECK (tipo IN ('eu_devo', 'me_deve')),
  CHECK (status IN ('ativa','encerrada','cancelada'))
);
ALTER TABLE "dividas_parceladas_grupos" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "dividas_parceladas_grupos" FORCE ROW LEVEL SECURITY;
REVOKE ALL ON "dividas_parceladas_grupos" FROM PUBLIC, anon, authenticated;
CREATE TABLE "empresas" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" TEXT NOT NULL,
  "tipo" TEXT,
  "valor_padrao" DOUBLE PRECISION DEFAULT 0,
  "ativa" BIGINT DEFAULT 1,
  "cor" TEXT,
  "icone" TEXT,
  "observacao" TEXT,
  "criado_em" TEXT DEFAULT to_char(timezone('America/Sao_Paulo', now()), 'YYYY-MM-DD HH24:MI:SS'),
  "atualizado_em" TEXT DEFAULT to_char(timezone('America/Sao_Paulo', now()), 'YYYY-MM-DD HH24:MI:SS'),
  "pagador_id" BIGINT,
  UNIQUE ("nome")
);
ALTER TABLE "empresas" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "empresas" FORCE ROW LEVEL SECURITY;
REVOKE ALL ON "empresas" FROM PUBLIC, anon, authenticated;
CREATE TABLE "faturas_cartao" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "cartao_id" BIGINT NOT NULL,
  "cartao_nome" TEXT NOT NULL,
  "competencia" TEXT NOT NULL,
  "vencimento" TEXT NOT NULL,
  "total" DOUBLE PRECISION NOT NULL DEFAULT 0,
  "status" TEXT NOT NULL DEFAULT 'aberta',
  "pago_em" TEXT,
  "criado_em" TEXT DEFAULT to_char(timezone('America/Sao_Paulo', now()), 'YYYY-MM-DD HH24:MI:SS'),
  "atualizado_em" TEXT DEFAULT to_char(timezone('America/Sao_Paulo', now()), 'YYYY-MM-DD HH24:MI:SS'),
  "forma_pagamento" TEXT DEFAULT '',
  "observacao_pagamento" TEXT DEFAULT '',
  CHECK (status IN ('aberta','fechada','paga','cancelada'))
);
ALTER TABLE "faturas_cartao" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "faturas_cartao" FORCE ROW LEVEL SECURITY;
REVOKE ALL ON "faturas_cartao" FROM PUBLIC, anon, authenticated;
CREATE TABLE "fechamentos_diarios" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "data" TEXT NOT NULL,
  "total_quantidade" BIGINT NOT NULL DEFAULT 0,
  "total_valor" DOUBLE PRECISION NOT NULL DEFAULT 0,
  "resumo_json" TEXT,
  "criado_em" TEXT DEFAULT to_char(timezone('America/Sao_Paulo', now()), 'YYYY-MM-DD HH24:MI:SS')
);
ALTER TABLE "fechamentos_diarios" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "fechamentos_diarios" FORCE ROW LEVEL SECURITY;
REVOKE ALL ON "fechamentos_diarios" FROM PUBLIC, anon, authenticated;
CREATE TABLE "fechamentos_mensais" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "referencia" TEXT NOT NULL,
  "qtd_diagnostico" BIGINT DEFAULT 0,
  "total_diagnostico" DOUBLE PRECISION DEFAULT 0,
  "qtd_perfecta" BIGINT DEFAULT 0,
  "total_perfecta" DOUBLE PRECISION DEFAULT 0,
  "qtd_email" BIGINT DEFAULT 0,
  "total_email" DOUBLE PRECISION DEFAULT 0,
  "qtd_padrao" BIGINT DEFAULT 0,
  "total_padrao" DOUBLE PRECISION DEFAULT 0,
  "qtd_ranon" BIGINT DEFAULT 0,
  "total_ranon" DOUBLE PRECISION DEFAULT 0,
  "qtd_global" BIGINT DEFAULT 0,
  "total_global" DOUBLE PRECISION DEFAULT 0,
  "fechado_em" TEXT,
  "snapshot_json" TEXT,
  "criado_em" TEXT DEFAULT to_char(timezone('America/Sao_Paulo', now()), 'YYYY-MM-DD HH24:MI:SS'),
  "atualizado_em" TEXT DEFAULT to_char(timezone('America/Sao_Paulo', now()), 'YYYY-MM-DD HH24:MI:SS'),
  UNIQUE ("referencia")
);
ALTER TABLE "fechamentos_mensais" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "fechamentos_mensais" FORCE ROW LEVEL SECURITY;
REVOKE ALL ON "fechamentos_mensais" FROM PUBLIC, anon, authenticated;
CREATE TABLE "gastos" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "data" TEXT NOT NULL,
  "descricao" TEXT NOT NULL,
  "valor" DOUBLE PRECISION NOT NULL,
  "categoria_id" BIGINT NOT NULL,
  "categoria_nome" TEXT NOT NULL,
  "forma_pagamento" TEXT NOT NULL,
  "conta_carteira" TEXT DEFAULT 'Principal',
  "status" TEXT NOT NULL DEFAULT 'pago',
  "observacao" TEXT,
  "criado_em" TEXT DEFAULT to_char(timezone('America/Sao_Paulo', now()), 'YYYY-MM-DD HH24:MI:SS'),
  "atualizado_em" TEXT DEFAULT to_char(timezone('America/Sao_Paulo', now()), 'YYYY-MM-DD HH24:MI:SS'),
  CHECK (status IN ('pago','pendente','cancelado'))
);
ALTER TABLE "gastos" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "gastos" FORCE ROW LEVEL SECURITY;
REVOKE ALL ON "gastos" FROM PUBLIC, anon, authenticated;
CREATE TABLE "investimento_movimentos" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "investimento_id" BIGINT NOT NULL,
  "tipo" TEXT NOT NULL,
  "valor" DOUBLE PRECISION NOT NULL,
  "data" TEXT NOT NULL,
  "observacao" TEXT,
  "criado_em" TEXT DEFAULT to_char(timezone('America/Sao_Paulo', now()), 'YYYY-MM-DD HH24:MI:SS'),
  "atualizado_em" TEXT DEFAULT to_char(timezone('America/Sao_Paulo', now()), 'YYYY-MM-DD HH24:MI:SS'),
  CHECK (tipo IN ('aporte', 'resgate', 'rendimento', 'ajuste')),
  CHECK (valor != 0)
);
ALTER TABLE "investimento_movimentos" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "investimento_movimentos" FORCE ROW LEVEL SECURITY;
REVOKE ALL ON "investimento_movimentos" FROM PUBLIC, anon, authenticated;
CREATE TABLE "investimentos" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" TEXT NOT NULL,
  "instituicao" TEXT NOT NULL,
  "conta_titular" TEXT NOT NULL,
  "ativo" BIGINT NOT NULL DEFAULT 1,
  "criado_em" TEXT DEFAULT to_char(timezone('America/Sao_Paulo', now()), 'YYYY-MM-DD HH24:MI:SS'),
  "atualizado_em" TEXT DEFAULT to_char(timezone('America/Sao_Paulo', now()), 'YYYY-MM-DD HH24:MI:SS'),
  CHECK (ativo IN (0, 1))
);
ALTER TABLE "investimentos" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "investimentos" FORCE ROW LEVEL SECURITY;
REVOKE ALL ON "investimentos" FROM PUBLIC, anon, authenticated;
CREATE TABLE "lancamentos_trabalho" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "empresa_id" BIGINT NOT NULL,
  "empresa_nome" TEXT NOT NULL,
  "quantidade" BIGINT NOT NULL,
  "valor_unitario" DOUBLE PRECISION NOT NULL,
  "total" DOUBLE PRECISION NOT NULL,
  "data" TEXT NOT NULL,
  "horario" TEXT,
  "status" TEXT NOT NULL DEFAULT 'produzido',
  "recebido_em" TEXT,
  "observacao" TEXT,
  "origem_fechamento_dia_id" BIGINT,
  "criado_em" TEXT DEFAULT to_char(timezone('America/Sao_Paulo', now()), 'YYYY-MM-DD HH24:MI:SS'),
  "atualizado_em" TEXT DEFAULT to_char(timezone('America/Sao_Paulo', now()), 'YYYY-MM-DD HH24:MI:SS'),
  CHECK (status IN ('produzido','fechado','recebido','cancelado'))
);
ALTER TABLE "lancamentos_trabalho" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "lancamentos_trabalho" FORCE ROW LEVEL SECURITY;
REVOKE ALL ON "lancamentos_trabalho" FROM PUBLIC, anon, authenticated;
CREATE TABLE "laudos_ranon" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "registro_paciente" TEXT NOT NULL,
  "valor_unitario" DOUBLE PRECISION NOT NULL,
  "total" DOUBLE PRECISION NOT NULL,
  "data" TEXT NOT NULL,
  "horario" TEXT,
  "status" TEXT NOT NULL DEFAULT 'produzido',
  "arquivo_excel_backup" TEXT,
  "observacao" TEXT,
  "criado_em" TEXT DEFAULT to_char(timezone('America/Sao_Paulo', now()), 'YYYY-MM-DD HH24:MI:SS'),
  "atualizado_em" TEXT DEFAULT to_char(timezone('America/Sao_Paulo', now()), 'YYYY-MM-DD HH24:MI:SS'),
  "recebido_em" TEXT,
  "quantidade" BIGINT DEFAULT 1,
  CHECK (status IN ('produzido','fechado','recebido','cancelado'))
);
ALTER TABLE "laudos_ranon" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "laudos_ranon" FORCE ROW LEVEL SECURITY;
REVOKE ALL ON "laudos_ranon" FROM PUBLIC, anon, authenticated;
CREATE TABLE "laudos_ranon_pendentes" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "registro_paciente" TEXT NOT NULL,
  "valor_unitario" DOUBLE PRECISION NOT NULL DEFAULT 2.00,
  "total" DOUBLE PRECISION NOT NULL,
  "data" TEXT NOT NULL,
  "horario" TEXT,
  "observacao" TEXT,
  "criado_em" TEXT DEFAULT to_char(timezone('America/Sao_Paulo', now()), 'YYYY-MM-DD HH24:MI:SS'),
  "atualizado_em" TEXT DEFAULT to_char(timezone('America/Sao_Paulo', now()), 'YYYY-MM-DD HH24:MI:SS'),
  "quantidade" BIGINT DEFAULT 1
);
ALTER TABLE "laudos_ranon_pendentes" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "laudos_ranon_pendentes" FORCE ROW LEVEL SECURITY;
REVOKE ALL ON "laudos_ranon_pendentes" FROM PUBLIC, anon, authenticated;
CREATE TABLE "lotes_trabalho_pendentes" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "empresa_id" BIGINT NOT NULL,
  "empresa_nome" TEXT NOT NULL,
  "quantidade" BIGINT NOT NULL,
  "valor_unitario" DOUBLE PRECISION NOT NULL,
  "total" DOUBLE PRECISION NOT NULL,
  "data" TEXT NOT NULL,
  "horario" TEXT,
  "observacao" TEXT,
  "criado_em" TEXT DEFAULT to_char(timezone('America/Sao_Paulo', now()), 'YYYY-MM-DD HH24:MI:SS'),
  "atualizado_em" TEXT DEFAULT to_char(timezone('America/Sao_Paulo', now()), 'YYYY-MM-DD HH24:MI:SS')
);
ALTER TABLE "lotes_trabalho_pendentes" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "lotes_trabalho_pendentes" FORCE ROW LEVEL SECURITY;
REVOKE ALL ON "lotes_trabalho_pendentes" FROM PUBLIC, anon, authenticated;
CREATE TABLE "pagadores" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" TEXT NOT NULL,
  "tipo_pessoa" TEXT NOT NULL DEFAULT 'medico',
  "documento" TEXT,
  "email" TEXT,
  "telefone" TEXT,
  "observacao" TEXT,
  "ativo" BIGINT DEFAULT 1,
  "criado_em" TEXT DEFAULT to_char(timezone('America/Sao_Paulo', now()), 'YYYY-MM-DD HH24:MI:SS'),
  "atualizado_em" TEXT DEFAULT to_char(timezone('America/Sao_Paulo', now()), 'YYYY-MM-DD HH24:MI:SS'),
  "tipo_recebimento" TEXT DEFAULT 'A definir',
  "conta_destino" TEXT DEFAULT 'A definir',
  UNIQUE ("nome")
);
ALTER TABLE "pagadores" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "pagadores" FORCE ROW LEVEL SECURITY;
REVOKE ALL ON "pagadores" FROM PUBLIC, anon, authenticated;
CREATE TABLE "parcelas_cartao" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "compra_id" BIGINT NOT NULL,
  "cartao_id" BIGINT NOT NULL,
  "cartao_nome" TEXT NOT NULL,
  "numero_parcela" BIGINT NOT NULL,
  "total_parcelas" BIGINT NOT NULL,
  "valor_parcela" DOUBLE PRECISION NOT NULL,
  "competencia" TEXT NOT NULL,
  "vencimento" TEXT NOT NULL,
  "status" TEXT NOT NULL DEFAULT 'aberta',
  "categoria_nome" TEXT NOT NULL,
  "descricao" TEXT NOT NULL,
  "criado_em" TEXT DEFAULT to_char(timezone('America/Sao_Paulo', now()), 'YYYY-MM-DD HH24:MI:SS'),
  "atualizado_em" TEXT DEFAULT to_char(timezone('America/Sao_Paulo', now()), 'YYYY-MM-DD HH24:MI:SS'),
  CHECK (status IN ('aberta','fechada','paga','cancelada'))
);
ALTER TABLE "parcelas_cartao" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "parcelas_cartao" FORCE ROW LEVEL SECURITY;
REVOKE ALL ON "parcelas_cartao" FROM PUBLIC, anon, authenticated;
CREATE TABLE "pessoas_dividas" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome_pessoa" TEXT NOT NULL,
  "tipo" TEXT NOT NULL,
  "valor" DOUBLE PRECISION NOT NULL,
  "motivo" TEXT NOT NULL,
  "data_combinada" TEXT NOT NULL,
  "status" TEXT NOT NULL DEFAULT 'pendente',
  "pago_recebido_em" TEXT,
  "observacao" TEXT,
  "criado_em" TEXT DEFAULT to_char(timezone('America/Sao_Paulo', now()), 'YYYY-MM-DD HH24:MI:SS'),
  "atualizado_em" TEXT DEFAULT to_char(timezone('America/Sao_Paulo', now()), 'YYYY-MM-DD HH24:MI:SS'),
  "parcela_atual" BIGINT DEFAULT 1,
  "total_parcelas" BIGINT DEFAULT 1,
  "grupo_parcelas_id" TEXT,
  CHECK (tipo IN ('eu_devo', 'me_deve')),
  CHECK (status IN ('pendente', 'pago', 'recebido', 'cancelado'))
);
ALTER TABLE "pessoas_dividas" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "pessoas_dividas" FORCE ROW LEVEL SECURITY;
REVOKE ALL ON "pessoas_dividas" FROM PUBLIC, anon, authenticated;
CREATE TABLE "receitas" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "data" TEXT NOT NULL,
  "descricao" TEXT NOT NULL,
  "valor" DOUBLE PRECISION NOT NULL,
  "origem" TEXT NOT NULL,
  "categoria_id" BIGINT,
  "categoria_nome" TEXT,
  "status" TEXT NOT NULL DEFAULT 'recebido',
  "recebido_em" TEXT,
  "vinculado_trabalho" BIGINT DEFAULT 0,
  "referencia_trabalho_tipo" TEXT,
  "referencia_trabalho_id" BIGINT,
  "observacao" TEXT,
  "criado_em" TEXT DEFAULT to_char(timezone('America/Sao_Paulo', now()), 'YYYY-MM-DD HH24:MI:SS'),
  "atualizado_em" TEXT DEFAULT to_char(timezone('America/Sao_Paulo', now()), 'YYYY-MM-DD HH24:MI:SS'),
  CHECK (status IN ('previsto', 'recebido', 'cancelado'))
);
ALTER TABLE "receitas" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "receitas" FORCE ROW LEVEL SECURITY;
REVOKE ALL ON "receitas" FROM PUBLIC, anon, authenticated;
ALTER TABLE "ajustes_retroativos" ADD FOREIGN KEY ("fechamento_mensal_id") REFERENCES "fechamentos_mensais" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "compras_cartao" ADD FOREIGN KEY ("categoria_id") REFERENCES "categorias" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "compras_cartao" ADD FOREIGN KEY ("cartao_id") REFERENCES "cartoes" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "contas_pagar" ADD FOREIGN KEY ("categoria_id") REFERENCES "categorias" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "empresas" ADD FOREIGN KEY ("pagador_id") REFERENCES "pagadores" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "faturas_cartao" ADD FOREIGN KEY ("cartao_id") REFERENCES "cartoes" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "gastos" ADD FOREIGN KEY ("categoria_id") REFERENCES "categorias" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "investimento_movimentos" ADD FOREIGN KEY ("investimento_id") REFERENCES "investimentos" ("id") ON DELETE RESTRICT ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "lancamentos_trabalho" ADD FOREIGN KEY ("origem_fechamento_dia_id") REFERENCES "fechamentos_diarios" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "lancamentos_trabalho" ADD FOREIGN KEY ("empresa_id") REFERENCES "empresas" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "lotes_trabalho_pendentes" ADD FOREIGN KEY ("empresa_id") REFERENCES "empresas" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "parcelas_cartao" ADD FOREIGN KEY ("cartao_id") REFERENCES "cartoes" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "parcelas_cartao" ADD FOREIGN KEY ("compra_id") REFERENCES "compras_cartao" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX idx_lancamentos_data ON lancamentos_trabalho(data);
CREATE INDEX idx_lancamentos_empresa ON lancamentos_trabalho(empresa_id);
CREATE INDEX idx_lancamentos_status ON lancamentos_trabalho(status);
CREATE INDEX idx_lotes_data ON lotes_trabalho_pendentes(data);
CREATE INDEX idx_ranon_data ON laudos_ranon(data);
CREATE INDEX idx_ranon_status ON laudos_ranon(status);
CREATE INDEX idx_ranon_pendentes_data ON laudos_ranon_pendentes(data);
CREATE INDEX idx_fechamentos_mensais_ref ON fechamentos_mensais(referencia);
CREATE INDEX idx_auditoria_tipo ON auditoria(tipo);
CREATE INDEX idx_fechamentos_data ON fechamentos_diarios(data);
CREATE INDEX idx_gastos_data ON gastos(data);
CREATE INDEX idx_gastos_status ON gastos(status);
CREATE INDEX idx_gastos_categoria ON gastos(categoria_id);
CREATE INDEX idx_compras_cartao_cartao ON compras_cartao(cartao_id);
CREATE INDEX idx_parcelas_cartao_compra ON parcelas_cartao(compra_id);
CREATE INDEX idx_parcelas_cartao_cartao_comp ON parcelas_cartao(cartao_id, competencia);
CREATE INDEX idx_parcelas_cartao_status ON parcelas_cartao(status);
CREATE INDEX idx_faturas_cartao_cartao_comp ON faturas_cartao(cartao_id, competencia);
CREATE INDEX idx_faturas_cartao_status ON faturas_cartao(status);
CREATE INDEX idx_contas_pagar_vencimento ON contas_pagar(vencimento);
CREATE INDEX idx_contas_pagar_status ON contas_pagar(status);
CREATE INDEX idx_contas_pagar_grupo ON contas_pagar(grupo_recorrencia_id);
CREATE INDEX idx_pessoas_dividas_nome ON pessoas_dividas(nome_pessoa);
CREATE INDEX idx_pessoas_dividas_tipo ON pessoas_dividas(tipo);
CREATE INDEX idx_pessoas_dividas_status ON pessoas_dividas(status);
CREATE INDEX idx_pessoas_dividas_data ON pessoas_dividas(data_combinada);
CREATE INDEX idx_receitas_data ON receitas(data);
CREATE INDEX idx_receitas_status ON receitas(status);
CREATE INDEX idx_receitas_origem ON receitas(origem);
CREATE INDEX idx_dividas_parc_nome ON dividas_parceladas_grupos(nome_pessoa);
CREATE INDEX idx_dividas_parc_status ON dividas_parceladas_grupos(status);
CREATE INDEX idx_investimentos_ativo ON investimentos(ativo);
CREATE INDEX idx_invest_mov_investimento_data
  ON investimento_movimentos(investimento_id, data, id);
CREATE INDEX idx_invest_mov_data ON investimento_movimentos(data);
COMMIT;
